service: ${file(../../project.env.yml):PROJECT_NAME}-graphicsmagick-layer

provider:
  name: aws
  versionFunctions: false
  stage: ${file(../../project.env.yml):STAGE}
  region: ${file(../../project.env.yml):REGION}
  deploymentBucket: ${self:provider.stage}-${file(../../project.env.yml):DEPLOYMENT_BUCKET_LAYER_GRAPHICSMAGICK}

layers:
  graphicsmagick:
    path: ./bin

resources:
  Outputs:
    GraphicsmagickLayerExport:
      Value:
        Ref: GraphicsmagickLambdaLayer
      Export:
        Name: GraphicsmagickLambdaLayer